### ISSUE TITLE
Missing project description on Github

### ISSUE THREAD

**Issue by lolgab** [keynmol/cloudflare-scalajs-template#1]
It would be nice to have a description
![image](https://user-images.githubusercontent.com/5793054/155592358-23884317-3188-4a0b-8a22-795121dc4e54.png)

**Comment by keynmol** [comment]
<img width="344" alt="image" src="https://user-images.githubusercontent.com/1052965/155614332-3e933877-4b7e-47dc-9481-b2f31165a777.png">
How does this look?

**Comment by lolgab** [comment]
It looks wonderful! ❤️
